### ISSUE TITLE
PYGAME 2 , SDL2: fix mixer errors, mixer.init(..., allowchanges=0) #861

### ISSUE THREAD

**Issue by yoyoberenguer** [Zulko/pianoputer#17]
When starting the program with PYGAME 2.00 version, I had the following exception:

Traceback (most recent call last):
  File "C:\Users\yoann\AppData\Local\Programs\Python\Python36\lib\site-packages\pygame\sndarray.py", line 94, in make_sound
    return numpysnd.make_sound(array)
AttributeError: 'NoneType' object has no attribute 'make_sound'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pianoputer.py", line 129, in <module>
    main()
  File "pianoputer.py", line 103, in main
    key_sound = dict(zip(keys, sounds))
  File "C:\Users\yoann\AppData\Local\Programs\Python\Python36\lib\site-packages\pygame\sndarray.py", line 97, in make_sound
    return numpysnd.make_sound(array)
  File "C:\Users\yoann\AppData\Local\Programs\Python\Python36\lib\site-packages\pygame\_numpysndarray.py", line 74, in make_sound
    return mixer.Sound(array=array)
ValueError: Array must be 2-dimensional for stereo mixer

This issue is related to[ PYGAME case : SDL2: fix mixer errors, mixer.init(..., allowchanges=0) #861](https://github.com/pygame/pygame/pull/861)

Suggestion to solve this issue (for both version of the program)
**************************
  for single track sound 
**************************
```
if int(pygame.version.ver[0]) >= 2:
    pygame.mixer.init(fps, -16, 1, 2048, allowedchanges=0)
else:
  pygame.mixer.init(fps, -16, 1, 2048)
```
**************************
   for stereo sound
**************************
```
if int(pygame.version.ver[0]) >= 2:
    pygame.mixer.init(fps, -16, 2, 2048, allowedchanges=0)
else:
    pygame.mixer.init(fps, -16, 2, 2048)
```

**Comment by spacether** [comment]
@yoyoberenguer can you try using the 2.0.0 version of pianoputer?
When I load in mono and stereo version into this new version I do not get the error in this issue so I think that this is fixed.
If I don't hear from you in the next week or two I will close this issue because I can't replicate it.

**Comment by yoyoberenguer** [comment]
@spacether,
Good day to you.
First nice job on the last version 2.0.0 of pianoputer, it looks so much better.

I can confirm the issue persist with pygame version 2.0 (I am attaching the screenshots proving it and also the resolution that will make your life easier) 
Here is the exception raised when loading (python 3.8 and pygame 2.0)
![CapturePython38](https://user-images.githubusercontent.com/38462796/102990221-f3f96a80-450e-11eb-8fb7-4ee9235bde24.PNG)

Here is the resolution (python 3.8 and pygame 2.0)
![CapturePython38_NoError](https://user-images.githubusercontent.com/38462796/102990318-112e3900-450f-11eb-8c51-c248fc33b9c4.PNG)

# audio
pygame.mixer.init(framerate_hz, BITS_32BIT, channels, allowedchanges=0)

Also I didn't have time to look into the code but I noticed a bug in the method get_audio_data

```audio_data, framerate_hz = soundfile.read(wav_path)
    try:
        channels = len(audio_data[0])
    except TypeError:
        channels = 1
    return audio_data, framerate_hz, channels```

For a single track, the numpy.ndarray will by shape e.g (31728, ) and for a stereo (31728, 2) 
The channel number is always referenced by the index 1 of the array (only for stereo or above) such as : 
channels = audio_data[1]
index 0 is the samples data length 
Your code above will always revert to a mono track and will never detect a stereo sound (and this explained why you could not replicate the issue).

```
def is_valid_array(array_)->bool:
    
    # DETERMINE IF THE ARRAY IS MONO OR STEREO AND RETURN TRUE IF VALID 
    
    # check the shape of an array
    if hasatttr(array_, 'shape'):
        if len(array_.shape) == 1: return True  # mono sound
        elif len(array_.shape) == 2:
            if array_.shape[1] <=2: return True # stereo sound
            else: return False
        else: return False  # more than 2 channel not implemented yet
    else: return False  # here Attribute Error, certainly not an ndarray type
```


```

**Comment by spacether** [comment]
Thank you for the explanation. Can you attach your stereo wav file?

**Comment by spacether** [comment]
Very weird, we are initializing the mixer with 1 channel for the mono wav file but on:
- windoes10pro pygame.mixer.get_init() returns (4800, -32, 2)
- and on macOs it reports (4800, -32, 1)

**Comment by spacether** [comment]
I have filed a pygame bug on this at https://github.com/pygame/pygame/issues/2417

**Comment by spacether** [comment]
A fix has been submitted for this usse at https://github.com/Zulko/pianoputer/pull/22

**Comment by spacether** [comment]
Thank you for submitting this problem and letting us know how to fix it!
With v2.0.1 this issue should be resolved
On WIndows10Pro I ran the tests and verified that generating 1, 2, and 4 channel wav files works and that we no longer get this exception. If this problem is still occurring can you re-open this issue?
